### ISSUE TITLE
Плохая реализация

### ISSUE THREAD

**Issue by SaberTrigun** [JinKazamma/EmployersData#1]
https://github.com/JinKazamma/Task1/blob/2da1b2cfc2eb8ec28f7d976ce9b259294070e1e7/main.cpp#L76-L99
Придумай как избавиться от кастов!!!

**Comment by JinKazamma** [comment]
почему это?
экономит много места под лишние перемены

**Comment by JinKazamma** [comment]
не хочу я от них избавляться, я специально под них код писал, в этом вся фишка

**Comment by SaberTrigun** [comment]
> почему это? экономит много места под лишние перемены

Ничего оно не экономит, подумай как от них избавиться)
